volumes:
  wordpress:
    name: wordpress_vol
    driver: local
    driver_opts:
      device: /home/alkane/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb_vol
    driver: local
    driver_opts:
      device: /home/alkane/data/mariadb
      o: bind
      type: none
  site:
    name: site_vol
    driver: local
    driver_opts:
      device: /home/alkane/data/site
      o: bind
      type : none

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    hostname: nginx
    build: 
      context: ./requirements/nginx/.
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
     - "443:443"
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    hostname: wordpress
    build:
      context: ./requirements/wordpress/.
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    hostname: mariadb
    build:
      context: ./requirements/mariadb/.
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

  redis:
    hostname: redis
    build:
      context: ./requirements/bonus/redis/.
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    networks:
      - inception
    restart: always
  ftp:
    hostname: ftp
    build:
      context: ./requirements/bonus/ftp/.
      args:
        FTP_USER: ftp_user
        FTP_PASSWORD: root
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    ports:
      - "21:21"
    networks:
      - inception
    restart: always
#  site:
#    hostname: site
#    build:
#      context: ./requirements/bonus/site/.
#      dockerfile: Dockerfile
#    volumes:
#      - site:/usr/share/nginx/html
#    ports:
#      - "3000:3000"
#    networks:
#      - inception
#    restart: always
  cadvisor:
    hostname: cadvisor
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: always
  adminer:
   hostname: adminer
   build:
     context: ./requirements/bonus/adminer
     dockerfile: Dockerfile
   ports:
     - "8000:8000"
   restart: always
   volumes:
     - wordpress:/var/www/html
   networks:
     - inception

