volumes:
  wordpress:
    name: wordpress_vol
    driver: local
    driver_opts:
      device: /Users/alistair/Documents/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb_vol
    driver: local
    driver_opts:
      device: /Users/alistair/Documents/data/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    hostname: nginx
    build: 
      context: ./requirements/nginx/.
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
     - "443:443"
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    hostname: wordpress
    build:
      context: ./requirements/wordpress/.
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    hostname: mariadb
    build:
      context: ./requirements/mariadb/.
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
