FROM debian:buster

RUN apt-get update -y
RUN apt install -y nginx && apt install openssl -y

COPY ./conf/default /etc/nginx/sites-available/
COPY ./tools/script.sh /

RUN chmod +x script.sh

CMD ["/script.sh"]